drive:
    ros__parameters:
        visualization: true
        model_path: "/lanefollowing/ros2_ws/src/lane_following/model/model.h5"
        model_path_class: "/lanefollowing/ros2_ws/src/lane_following/model/model1.h5"
        model_path_reg: "/lanefollowing/ros2_ws/src/lane_following/model/model2.h5"
        center_camera_topic: "/simulator/sensor/camera/center/image/compressed"
        depth_center_topic: '/simulator/sensor/depth_camera/center/image/compressed'
        left_camera_topic: '/simulator/sensor/camera/left90/image/compressed'
        depth_left_topic: '/simulator/sensor/depth_camera/left90/image/compressed'
        right_camera_topic: "/simulator/sensor/camera/right90/image/compressed"
        depth_right_topic: '/simulator/sensor/depth_camera/right90/image/compressed'
        seg_camera_topic: "/simulator/sensor/segmentation_camera"
        control_topic: "/lanefollowing/control_cmd" 
        steer_ratio: 1.
        steering_wheel_single_direction_max: 360.
        wheel_base: 2.836747

